// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("5.9.0.0")]
[assembly: AssemblyFileVersionAttribute("5.9.0.0")]
[assembly: AssemblyInformationalVersionAttribute("5.8.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "5.8.1.0";
        internal const System.String AssemblyFileVersion = "5.8.1.0";
        internal const System.String AssemblyInformationalVersion = "5.8.1.0 4c92af";
    }
}
